version: '3.8'

services:
  ebay-soap:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ws/ebay.wsdl"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
