//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.21 at 09:55:25 PM EEST 
//


package com.ebay.soap.types;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Condition.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="Condition"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NEW"/&gt;
 *     &lt;enumeration value="LIKE_NEW"/&gt;
 *     &lt;enumeration value="GOOD"/&gt;
 *     &lt;enumeration value="FAIR"/&gt;
 *     &lt;enumeration value="POOR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Condition")
@XmlEnum
public enum Condition {

    NEW,
    LIKE_NEW,
    GOOD,
    FAIR,
    POOR;

    public String value() {
        return name();
    }

    public static Condition fromValue(String v) {
        return valueOf(v);
    }

}
