//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.21 at 10:30:51 PM EEST 
//


package com.ebay.soap.types;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ebay.soap.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegisterUserRequest_QNAME = new QName("http://soap.ebay.com/types", "registerUserRequest");
    private final static QName _RegisterUserResponse_QNAME = new QName("http://soap.ebay.com/types", "registerUserResponse");
    private final static QName _CreateListingRequest_QNAME = new QName("http://soap.ebay.com/types", "createListingRequest");
    private final static QName _CreateListingResponse_QNAME = new QName("http://soap.ebay.com/types", "createListingResponse");
    private final static QName _GetListingRequest_QNAME = new QName("http://soap.ebay.com/types", "getListingRequest");
    private final static QName _GetListingResponse_QNAME = new QName("http://soap.ebay.com/types", "getListingResponse");
    private final static QName _SearchListingsRequest_QNAME = new QName("http://soap.ebay.com/types", "searchListingsRequest");
    private final static QName _SearchListingsResponse_QNAME = new QName("http://soap.ebay.com/types", "searchListingsResponse");
    private final static QName _PlaceBidRequest_QNAME = new QName("http://soap.ebay.com/types", "placeBidRequest");
    private final static QName _PlaceBidResponse_QNAME = new QName("http://soap.ebay.com/types", "placeBidResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ebay.soap.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterUserRequest }
     * 
     */
    public RegisterUserRequest createRegisterUserRequest() {
        return new RegisterUserRequest();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link CreateListingRequest }
     * 
     */
    public CreateListingRequest createCreateListingRequest() {
        return new CreateListingRequest();
    }

    /**
     * Create an instance of {@link CreateListingResponse }
     * 
     */
    public CreateListingResponse createCreateListingResponse() {
        return new CreateListingResponse();
    }

    /**
     * Create an instance of {@link GetListingRequest }
     * 
     */
    public GetListingRequest createGetListingRequest() {
        return new GetListingRequest();
    }

    /**
     * Create an instance of {@link GetListingResponse }
     * 
     */
    public GetListingResponse createGetListingResponse() {
        return new GetListingResponse();
    }

    /**
     * Create an instance of {@link SearchListingsRequest }
     * 
     */
    public SearchListingsRequest createSearchListingsRequest() {
        return new SearchListingsRequest();
    }

    /**
     * Create an instance of {@link SearchListingsResponse }
     * 
     */
    public SearchListingsResponse createSearchListingsResponse() {
        return new SearchListingsResponse();
    }

    /**
     * Create an instance of {@link BidRequest }
     * 
     */
    public BidRequest createBidRequest() {
        return new BidRequest();
    }

    /**
     * Create an instance of {@link PlaceBidResponse }
     * 
     */
    public PlaceBidResponse createPlaceBidResponse() {
        return new PlaceBidResponse();
    }

    /**
     * Create an instance of {@link Listing }
     * 
     */
    public Listing createListing() {
        return new Listing();
    }

    /**
     * Create an instance of {@link Bid }
     * 
     */
    public Bid createBid() {
        return new Bid();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterUserRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegisterUserRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "registerUserRequest")
    public JAXBElement<RegisterUserRequest> createRegisterUserRequest(RegisterUserRequest value) {
        return new JAXBElement<RegisterUserRequest>(_RegisterUserRequest_QNAME, RegisterUserRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link User }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "registerUserResponse")
    public JAXBElement<User> createRegisterUserResponse(User value) {
        return new JAXBElement<User>(_RegisterUserResponse_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateListingRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateListingRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "createListingRequest")
    public JAXBElement<CreateListingRequest> createCreateListingRequest(CreateListingRequest value) {
        return new JAXBElement<CreateListingRequest>(_CreateListingRequest_QNAME, CreateListingRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateListingResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateListingResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "createListingResponse")
    public JAXBElement<CreateListingResponse> createCreateListingResponse(CreateListingResponse value) {
        return new JAXBElement<CreateListingResponse>(_CreateListingResponse_QNAME, CreateListingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetListingRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetListingRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "getListingRequest")
    public JAXBElement<GetListingRequest> createGetListingRequest(GetListingRequest value) {
        return new JAXBElement<GetListingRequest>(_GetListingRequest_QNAME, GetListingRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetListingResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetListingResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "getListingResponse")
    public JAXBElement<GetListingResponse> createGetListingResponse(GetListingResponse value) {
        return new JAXBElement<GetListingResponse>(_GetListingResponse_QNAME, GetListingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchListingsRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchListingsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "searchListingsRequest")
    public JAXBElement<SearchListingsRequest> createSearchListingsRequest(SearchListingsRequest value) {
        return new JAXBElement<SearchListingsRequest>(_SearchListingsRequest_QNAME, SearchListingsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchListingsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchListingsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "searchListingsResponse")
    public JAXBElement<SearchListingsResponse> createSearchListingsResponse(SearchListingsResponse value) {
        return new JAXBElement<SearchListingsResponse>(_SearchListingsResponse_QNAME, SearchListingsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BidRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BidRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "placeBidRequest")
    public JAXBElement<BidRequest> createPlaceBidRequest(BidRequest value) {
        return new JAXBElement<BidRequest>(_PlaceBidRequest_QNAME, BidRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaceBidResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PlaceBidResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "placeBidResponse")
    public JAXBElement<PlaceBidResponse> createPlaceBidResponse(PlaceBidResponse value) {
        return new JAXBElement<PlaceBidResponse>(_PlaceBidResponse_QNAME, PlaceBidResponse.class, null, value);
    }

}
