//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.21 at 09:55:25 PM EEST 
//


package com.ebay.soap.types;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ebay.soap.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegisterUserRequest_QNAME = new QName("http://soap.ebay.com/types", "registerUserRequest");
    private final static QName _RegisterUserResponse_QNAME = new QName("http://soap.ebay.com/types", "registerUserResponse");
    private final static QName _LoginRequest_QNAME = new QName("http://soap.ebay.com/types", "loginRequest");
    private final static QName _LoginResponse_QNAME = new QName("http://soap.ebay.com/types", "loginResponse");
    private final static QName _GetUserResponse_QNAME = new QName("http://soap.ebay.com/types", "getUserResponse");
    private final static QName _GetCategoriesResponse_QNAME = new QName("http://soap.ebay.com/types", "getCategoriesResponse");
    private final static QName _CreateListingRequest_QNAME = new QName("http://soap.ebay.com/types", "createListingRequest");
    private final static QName _CreateListingResponse_QNAME = new QName("http://soap.ebay.com/types", "createListingResponse");
    private final static QName _SearchListingsRequest_QNAME = new QName("http://soap.ebay.com/types", "searchListingsRequest");
    private final static QName _SearchListingsResponse_QNAME = new QName("http://soap.ebay.com/types", "searchListingsResponse");
    private final static QName _GetListingRequest_QNAME = new QName("http://soap.ebay.com/types", "getListingRequest");
    private final static QName _GetListingResponse_QNAME = new QName("http://soap.ebay.com/types", "getListingResponse");
    private final static QName _PlaceBidRequest_QNAME = new QName("http://soap.ebay.com/types", "placeBidRequest");
    private final static QName _PlaceBidResponse_QNAME = new QName("http://soap.ebay.com/types", "placeBidResponse");
    private final static QName _GetBidHistoryRequest_QNAME = new QName("http://soap.ebay.com/types", "getBidHistoryRequest");
    private final static QName _GetBidHistoryResponse_QNAME = new QName("http://soap.ebay.com/types", "getBidHistoryResponse");
    private final static QName _BuyNowRequest_QNAME = new QName("http://soap.ebay.com/types", "buyNowRequest");
    private final static QName _BuyNowResponse_QNAME = new QName("http://soap.ebay.com/types", "buyNowResponse");
    private final static QName _GetUserOrdersRequest_QNAME = new QName("http://soap.ebay.com/types", "getUserOrdersRequest");
    private final static QName _GetUserOrdersResponse_QNAME = new QName("http://soap.ebay.com/types", "getUserOrdersResponse");
    private final static QName _EbayFault_QNAME = new QName("http://soap.ebay.com/types", "ebayFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ebay.soap.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterUserRequest }
     * 
     */
    public RegisterUserRequest createRegisterUserRequest() {
        return new RegisterUserRequest();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link GetCategoriesRequest }
     * 
     */
    public GetCategoriesRequest createGetCategoriesRequest() {
        return new GetCategoriesRequest();
    }

    /**
     * Create an instance of {@link GetCategoriesResponse }
     * 
     */
    public GetCategoriesResponse createGetCategoriesResponse() {
        return new GetCategoriesResponse();
    }

    /**
     * Create an instance of {@link CreateListingRequest }
     * 
     */
    public CreateListingRequest createCreateListingRequest() {
        return new CreateListingRequest();
    }

    /**
     * Create an instance of {@link Listing }
     * 
     */
    public Listing createListing() {
        return new Listing();
    }

    /**
     * Create an instance of {@link SearchListingsRequest }
     * 
     */
    public SearchListingsRequest createSearchListingsRequest() {
        return new SearchListingsRequest();
    }

    /**
     * Create an instance of {@link SearchListingsResponse }
     * 
     */
    public SearchListingsResponse createSearchListingsResponse() {
        return new SearchListingsResponse();
    }

    /**
     * Create an instance of {@link GetListingRequest }
     * 
     */
    public GetListingRequest createGetListingRequest() {
        return new GetListingRequest();
    }

    /**
     * Create an instance of {@link PlaceBidRequest }
     * 
     */
    public PlaceBidRequest createPlaceBidRequest() {
        return new PlaceBidRequest();
    }

    /**
     * Create an instance of {@link Bid }
     * 
     */
    public Bid createBid() {
        return new Bid();
    }

    /**
     * Create an instance of {@link GetBidHistoryRequest }
     * 
     */
    public GetBidHistoryRequest createGetBidHistoryRequest() {
        return new GetBidHistoryRequest();
    }

    /**
     * Create an instance of {@link GetBidHistoryResponse }
     * 
     */
    public GetBidHistoryResponse createGetBidHistoryResponse() {
        return new GetBidHistoryResponse();
    }

    /**
     * Create an instance of {@link BuyNowRequest }
     * 
     */
    public BuyNowRequest createBuyNowRequest() {
        return new BuyNowRequest();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link GetUserOrdersRequest }
     * 
     */
    public GetUserOrdersRequest createGetUserOrdersRequest() {
        return new GetUserOrdersRequest();
    }

    /**
     * Create an instance of {@link GetUserOrdersResponse }
     * 
     */
    public GetUserOrdersResponse createGetUserOrdersResponse() {
        return new GetUserOrdersResponse();
    }

    /**
     * Create an instance of {@link EbayFault }
     * 
     */
    public EbayFault createEbayFault() {
        return new EbayFault();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterUserRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegisterUserRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "registerUserRequest")
    public JAXBElement<RegisterUserRequest> createRegisterUserRequest(RegisterUserRequest value) {
        return new JAXBElement<RegisterUserRequest>(_RegisterUserRequest_QNAME, RegisterUserRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link User }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "registerUserResponse")
    public JAXBElement<User> createRegisterUserResponse(User value) {
        return new JAXBElement<User>(_RegisterUserResponse_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LoginRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "loginRequest")
    public JAXBElement<LoginRequest> createLoginRequest(LoginRequest value) {
        return new JAXBElement<LoginRequest>(_LoginRequest_QNAME, LoginRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LoginResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "loginResponse")
    public JAXBElement<LoginResponse> createLoginResponse(LoginResponse value) {
        return new JAXBElement<LoginResponse>(_LoginResponse_QNAME, LoginResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link User }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "getUserResponse")
    public JAXBElement<User> createGetUserResponse(User value) {
        return new JAXBElement<User>(_GetUserResponse_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCategoriesResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCategoriesResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "getCategoriesResponse")
    public JAXBElement<GetCategoriesResponse> createGetCategoriesResponse(GetCategoriesResponse value) {
        return new JAXBElement<GetCategoriesResponse>(_GetCategoriesResponse_QNAME, GetCategoriesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateListingRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateListingRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "createListingRequest")
    public JAXBElement<CreateListingRequest> createCreateListingRequest(CreateListingRequest value) {
        return new JAXBElement<CreateListingRequest>(_CreateListingRequest_QNAME, CreateListingRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Listing }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Listing }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "createListingResponse")
    public JAXBElement<Listing> createCreateListingResponse(Listing value) {
        return new JAXBElement<Listing>(_CreateListingResponse_QNAME, Listing.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchListingsRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchListingsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "searchListingsRequest")
    public JAXBElement<SearchListingsRequest> createSearchListingsRequest(SearchListingsRequest value) {
        return new JAXBElement<SearchListingsRequest>(_SearchListingsRequest_QNAME, SearchListingsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchListingsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchListingsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "searchListingsResponse")
    public JAXBElement<SearchListingsResponse> createSearchListingsResponse(SearchListingsResponse value) {
        return new JAXBElement<SearchListingsResponse>(_SearchListingsResponse_QNAME, SearchListingsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetListingRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetListingRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "getListingRequest")
    public JAXBElement<GetListingRequest> createGetListingRequest(GetListingRequest value) {
        return new JAXBElement<GetListingRequest>(_GetListingRequest_QNAME, GetListingRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Listing }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Listing }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "getListingResponse")
    public JAXBElement<Listing> createGetListingResponse(Listing value) {
        return new JAXBElement<Listing>(_GetListingResponse_QNAME, Listing.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaceBidRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PlaceBidRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "placeBidRequest")
    public JAXBElement<PlaceBidRequest> createPlaceBidRequest(PlaceBidRequest value) {
        return new JAXBElement<PlaceBidRequest>(_PlaceBidRequest_QNAME, PlaceBidRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Bid }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Bid }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "placeBidResponse")
    public JAXBElement<Bid> createPlaceBidResponse(Bid value) {
        return new JAXBElement<Bid>(_PlaceBidResponse_QNAME, Bid.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBidHistoryRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetBidHistoryRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "getBidHistoryRequest")
    public JAXBElement<GetBidHistoryRequest> createGetBidHistoryRequest(GetBidHistoryRequest value) {
        return new JAXBElement<GetBidHistoryRequest>(_GetBidHistoryRequest_QNAME, GetBidHistoryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBidHistoryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetBidHistoryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "getBidHistoryResponse")
    public JAXBElement<GetBidHistoryResponse> createGetBidHistoryResponse(GetBidHistoryResponse value) {
        return new JAXBElement<GetBidHistoryResponse>(_GetBidHistoryResponse_QNAME, GetBidHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuyNowRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BuyNowRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "buyNowRequest")
    public JAXBElement<BuyNowRequest> createBuyNowRequest(BuyNowRequest value) {
        return new JAXBElement<BuyNowRequest>(_BuyNowRequest_QNAME, BuyNowRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Order }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Order }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "buyNowResponse")
    public JAXBElement<Order> createBuyNowResponse(Order value) {
        return new JAXBElement<Order>(_BuyNowResponse_QNAME, Order.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserOrdersRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetUserOrdersRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "getUserOrdersRequest")
    public JAXBElement<GetUserOrdersRequest> createGetUserOrdersRequest(GetUserOrdersRequest value) {
        return new JAXBElement<GetUserOrdersRequest>(_GetUserOrdersRequest_QNAME, GetUserOrdersRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserOrdersResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetUserOrdersResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "getUserOrdersResponse")
    public JAXBElement<GetUserOrdersResponse> createGetUserOrdersResponse(GetUserOrdersResponse value) {
        return new JAXBElement<GetUserOrdersResponse>(_GetUserOrdersResponse_QNAME, GetUserOrdersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EbayFault }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EbayFault }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.ebay.com/types", name = "ebayFault")
    public JAXBElement<EbayFault> createEbayFault(EbayFault value) {
        return new JAXBElement<EbayFault>(_EbayFault_QNAME, EbayFault.class, null, value);
    }

}
